name: Pre-Commit Hooks

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ "3.12" ]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - name: Run pre-commit hooks
        run: pre-commit run --all-files

      # Run programs as a mean of testing.

      - name: Run programs in algorithms
        run: python algorithms/rendezvous_hashing_main.py

      - name: Run programs in python_asyncio
        run: |
          python python_asyncio/coroutines_basics_main.py
          python python_asyncio/producer_consumer_batch_main.py
